### PR TITLE
Post App: External API and Tests

### PR DESCRIPTION
**Pull request by berfinsimsekk**
The app now provides support for weather forecast in Istanbul for external API task, you can see the temperature on the homepage. Also, I wrote the unit tests inside the tests.py file.

The code for the app needs to be reviewed by 2 people before merging as discussed in meeting 15.

### CODE REVIEW

**Review by yusuferdemnacar — CHANGES_REQUESTED** [review]
The app seems OK, however, there is a little detail that I found. The app UI seems to respond as if it created the post even if you enter an illegal pot title/description/label. I tried to insert a title with length >500, a description with length >2000 and a label with length >50. In all cases I got the green box saying that I successfully created a post even though the app did not add the post to the database.

**Comment by yusuferdemnacar** [comment]
Additionally, could you please list what methods your app should support for each request method?

**GET**

- [ ] postindex
- [ ] indexhome
- [ ] getPost
- [ ] createPost


**POST**

- [ ] postindex
- [ ] indexhome
- [ ] getPost
- [ ] createPost

This is for testing the requests using curl/postman.

**Comment by berfinsimsekk** [comment]
I updated views.py and postindex.html files. Now, the app gives error if the user enters illegal post title/description/label. @yusuferdemnacar thank you for noticing.

**Review by yusuferdemnacar — APPROVED** [review]
I reviewed the final changes locally by fetching and merging. They look fine. Thank you for your work.

I will now merge and delete the branch.

**Pull request merged**
