### PR TITLE
Advice App API Documentation

### PR DESCRIPTION
**Pull request by yusuferdemnacar**
Added API documentation for the advice app. The documentation is at the /advicedocs URL. Updated the requirements.txt to run it. The new package added is drf_yasg 1.20.0.

### CODE REVIEW

**Review by berfinsimsekk — APPROVED** [review]
I think everything is okay and working correctly. Thank you for your effort!

**Review by LehabuL — APPROVED** [review]
The documentation page works and looks fine. You have changed more than adding drf_yasg in the requirements file but it did not effect the execution so no problem there.

**Comment by yusuferdemnacar** [comment]
> The documentation page works and looks fine. You have changed more than adding drf_yasg in the requirements file but it did not effect the execution so no problem there.

Yeah, probably some dependencies, I re-generated the file with pip freeze.

Thanks for the reviews!

**Review by araldortogul — APPROVED** [review]
The documentation page looks great @yusuferdemnacar. You can merge `docs` into `master`.

**Pull request merged**
