### PR TITLE
Drugs and Side Effects App 

### PR DESCRIPTION
**Pull request by BPamukcuoglu**

### CODE REVIEW

**Comment by araldortogul** [comment]
I have reviewed the **Drug & Side Effects API** and everything works great! The app provides a sufficient front end, and POST and GET methods work without any problem. Thank you for your effort @BPamukcuoglu.

**Comment by yasirdikbas** [comment]
As far as I reviewed the Drugs and Side effect  api everything seems to be working perfectly fine. The api is aligned with the api requirements to be developed. Both front-end and backend are functioning as wanted. Nice  work overall.

**Comment by yasirdikbas** [comment]
As far as I reviewed the Drugs and Side effect api everything seems to be working perfectly fine. The api is aligned with the api requirements to be developed. Both front-end and backend are functioning as wanted. Nice work overall.

**Review by yasirdikbas — APPROVED** [review]
I have checked the code and everything seems to be perfect.

**Pull request merged**
