### PR TITLE
Edit Post Comment Endpoint Implementation Merge

### PR DESCRIPTION
**Pull request by artun-akdogan**
Endpoint API for edit comment/post has been added by PUT method. Nearly all of the sections except id's and owner can be changed with this new method. If no key in form has been given, old values are preserved. Also, a new database key, last_update_at, has been added to keep track of updates. Besides, there are refactors and changes in post method too.

Please note that tests and documents will be added via [Writing Content Manager's Documentation and Tests](https://github.com/bounswe/bounswe2022group6/issues/309)

### CODE REVIEW

**Review by yusuferdemnacar — COMMENTED** [review]
I have read the code. It looks fine. I will merge it as soon as I get to test it.

**Comment by artun-akdogan** [comment]
Please review the following bugfix. I have also added json content-type to be enabled for testing code.

**Review by yusuferdemnacar — CHANGES_REQUESTED** [review]
I have tested the changes and found a small bug. It seems that the server does not handle the case when the post with the given id does not exist.

**Comment by yusuferdemnacar** [comment]
I have fixed the bug. You can find the commit here, b46f575d88fa90deb513bda77e7abd7626fa3f62.

**Review by yusuferdemnacar — APPROVED** [review]

**Pull request merged**
