### PR TITLE
Profile View/Edit Functionalities Implemented

### PR DESCRIPTION
**Pull request by yusuferdemnacar**
The endpoints for the profile viewing and editing functionalities are implemented.

### Profile View
To receive the information of a user, the user has to be authenticated (logged in). If the user is authenticated, they can get all the information except the password hash by making a GET request to the profile or profile/ endpoint.

### Profile Edit
To change the information in an account, the user has to be authenticated (logged in). If the user is authenticated, they can change the information on their account by making a PATCH request to the profile or profile/ endpoint with the necessary form data present in the body of the request.

If a key (field name) is not present in the form data, it means that the value in the account will not change. If a key is present but its value is an empty string, it means that the value in the account will be set to null (possible only for the optional fields). If a key is present and the value is not the empty string, then the value in the account is changed to the sent value.

This way users can use the same endpoint for removing information from their accounts.

**Tasks**
- [x] Implementing view profile
- [x] Implementing edit profile
- [x] Writing tests
- [x] Creating API documentation

### CODE REVIEW

**Comment by yusuferdemnacar** [comment]
The implementation part is done.

**Deadline for the remaining tasks**: 23.11.2022

**Review by artun-akdogan — APPROVED** [review]
I have reviewed the code, and it seems OK. Thank you for your hard work. I believe documentation and testing parts can be committed with another pull request as rapid development of features is essential.

**Comment by yusuferdemnacar** [comment]
> I have spotted a bug in the patch method of the Profile class which returns success even if there is no change to the birth date. I am working on it.

The bug is fixed. You can find the commit here, d5d0faa2738df45cf38709c285940697e9b65d53.

**Comment by yusuferdemnacar** [comment]
The tests and the API document for the profile endpoint are ready. You can find the commits here, 3db34955c11c44df469a9a7b999e04466ba953aa, 999bdc96ad01fa13c04498a1e5ae7f6b40478ee0.

**Pull request merged**
