### PR TITLE
Frontend/feature/edit profile page

### PR DESCRIPTION
**Pull request by berfinsimsekk**
GET and POST methods for backend are integrated with frontend of Profile page. New text boxes are added for extra information of the user.

### CODE REVIEW

**Review by Aliqaan — CHANGES_REQUESTED** [review]
Thanks for your effort. I noticed two things regarding the functionality.

- Seems like the following user information doesnt update after hitting the edit button:

  * username
  * verified as a doctor slide
  * diploma id
  * profession
  * birthday 

- It doesnt update when an information is deleted with selecting it all and then deleting. Example: in the name field using CTRL + A and then hitting escape button.

**Comment by Aliqaan** [comment]
Also adding error messages would be nice for user experience

**Comment by berfinsimsekk** [comment]
Thanks for your review. I fixed diploma id and birthday change problem. But I think backend doesn't provide updating for username, verification of a doctor, message allowing and notification allowing. Maybe @yusuferdemnacar might inform us.

**Comment by berfinsimsekk** [comment]
I have tried to fix profession change problem but I think there is a problem with backend. Before we consult to the backend team, @Aliqaan can you try to fix it? If you can't we can speak with backend team.

**Comment by berfinsimsekk** [comment]
Also I didn't add error messages because the only error message that our database has about birthday. Since I used type="date" in birthday text input, a user cannot enter a false date. 
If our backend team add more error messages for POST method, we can add them too.
What we can do about this @yusuferdemnacar ?

**Comment by Aliqaan** [comment]
Backend is working as expected, I found and fixed the mentioned problems. I could't find a solution to ctrl+a delete, you can try to fix it. If you can that's great, otherwise we can try to fix it later since it is not a big problem for now.
Please remove the unrelevant log comments and let me know if you can find a solution to the ctrl+a issue.

**Comment by berfinsimsekk** [comment]
I also couldn't find a solution to ctrl+a problem, we can focus on it later. I removed unrelevant log comments and also made username field not editable, it is read-only because a user cannot change her username according to our requirements.
I think everything is okay, I merging and closing the pull request. Thanks

**Comment by LehabuL** [comment]
I also checked the latest version and it is working as intended. One small suggestion is that we can delete the "Your changes have been successfully saved." message after a delay, but it is not an urgent matter right now.

**Pull request merged**
