### PR TITLE
User App: External API and Tests

### PR DESCRIPTION
**Pull request by haticerk**
Requirements listed in #124 and #115 are met.

The app now provides support for daily horoscopes for external api task. Also, some minor updates are done in templates. Finally, I wrote the unit tests.

The code for the app needs to be reviewed by 2 people before merging as discussed in meeting 15.

### CODE REVIEW

**Review by berfinsimsekk — APPROVED** [review]
External API and tests are working fine. Daily horoscope API is very cool! Thanks.

**Comment by yusuferdemnacar** [comment]
I ran your code and it looks fine, however, I have some questions before I approve;

- I could create multiple users with the same e-mail, was this intended?
- Could you please list what methods your app support for each request method?

**GET**

- [ ] user-home
- [ ] user-list
- [ ] user-detail
- [ ] user-detail-worker
- [ ] user-create
- [ ] user-create-worker 

**POST**

- [ ] user-home
- [ ] user-list
- [ ] user-detail
- [ ] user-detail-worker
- [ ] user-create
- [ ] user-create-worker 

This is for more in-depth testing. Otherwise, the app works just fine.

**Review by yusuferdemnacar — CHANGES_REQUESTED** [review]
Additionally, the app returns status code 200 even if the user creation fails. I believe it would be better for it to return some other code (maybe 422), though I'm not sure, so I will leave it to you.

**Comment by haticerk** [comment]
@yusuferdemnacar, for the practice-app, I did not check uniqueness of mail addresses. However, I will add it to make more similar to real app.  Also, I will change return status codes with appropiate ones. Thanks for your comment!

**Review by yusuferdemnacar — APPROVED** [review]
I reviewed the final changes locally by fetching and merging. They look fine. Thank you for your work.

**Pull request merged**
