### PR TITLE
Hospital List App (First Draft)

### PR DESCRIPTION
**Pull request by yasirdikbas**
I roughly completed all the necessary things but there might be some problems about files or codes, I kindly ask for review of my code so that I can change it if there are problems.

### CODE REVIEW

**Comment by BPamukcuoglu** [comment]
I inspected the project, thanks for your work it works nice and color you choose is awesome. However, you coded it as an another application instead of adding it to our main practice_app. You can inspect the one of others done from the master branch. I also run the tests eveyrthing looks alright, thanks for your work and time 👍

**Review by BPamukcuoglu — CHANGES_REQUESTED** [review]
Need to add this app to our main practice_app.

**Comment by aeren02** [comment]
I have reviewed this pull request and as far as I can see, your changes after the feedback given by @BPamukcuoglu were sufficient. I couldn't find any errors in the current version and therefore approving this request. Thanks for your hard work.

**Review by aeren02 — APPROVED** [review]

**Review by BPamukcuoglu — APPROVED** [review]
Everything looks alright now! Thanks for your effort @yasirdikbas good job 👍

**Pull request merged**
