### PR TITLE
RegisteredUser Model Updated and Account Model Created

### PR DESCRIPTION
**Pull request by yusuferdemnacar**
I have updated the RegisteredUser model and added a new Account model to better reflect the class diagram.
The Account model has the following optional fields that are not required for registration:

* firstname
* lastname
* phone_number
* verified_as_doctor
* profile_picture
* profession
* location
* diplomaID

However, due to how authentication works in Django, I have not moved the mandatory fields to the Account model.

Additionally, the RegisteredUser now has the following option fields related to how their account should function:
* is_messaging_allowed
* is_notification_allowed

**Review Deadline:** 12.11.2022

### CODE REVIEW

**Comment by yusuferdemnacar** [comment]
In the current state of this code, the account of a registered user is deleted if the registered user is deleted, however, if the account is deleted, the registered user stays. Should I change it so that both get deleted in each case?

**Comment by artun-akdogan** [comment]
Thank you for your hard work. I only proposed one point. Other than that, it seems to work flawlessly. Also, it is much more structured than before. Future work may include adding password check for setting a minimum length in views.py. After my proposition is either rejected or approved, I will approve this pull request.

**Comment by artun-akdogan** [comment]
> In the current state of this code, the account of a registered user is deleted if the registered user is deleted, however, if the account is deleted, the registered user stays. Should I change it so that both get deleted in each case?

A registered user may need to reset his/her account. In this case, we can simply delete Account model and add another one. Registration information however, must be kept as long as user is using his/her account. Therefore, in a case of registration information deletion, Account model should be deleted immediately. 

In short, I think that this type of relationship between models is appropriate.

**Comment by yusuferdemnacar** [comment]
> Thank you for your hard work. I only proposed one point. Other than that, it seems to work flawlessly. Also, it is much more structured than before. Future work may include adding password check for setting a minimum length in views.py. After my proposition is either rejected or approved, I will approve this pull request.

If the proposition you mentioned is the password check, how should I implement it? what kind of password constraints should it have? I would propose using [django-passwords](https://github.com/dstufft/django-passwords)' password field which provides an easy to use password validator.

If the proposition you mentioned is something else, I could not find it. can you elaborate?

**Comment by artun-akdogan** [comment]
> If the proposition you mentioned is the password check, how should I implement it? what kind of password constraints should it have? I would propose using [django-passwords](https://github.com/dstufft/django-passwords)' password field which provides an easy to use password validator.

I proposed adding an "if check" on registration if user has entered a password longer than x characters before hashing.

**Comment by yusuferdemnacar** [comment]
I added your recommendation. You can see the commit here, befdbebe2ecf9c1330821349331fdb7a9772eba4.

**Review by artun-akdogan — APPROVED** [review]
Thanks again for the work. Everything seems fine now.

**Pull request merged**
