### PR TITLE
Added Home Feed

### PR DESCRIPTION
**Pull request by araldortogul**
The home feed has:
- search bar
- chatbot icon
- refresh control
- post previews with labels

Please note that not all the buttons are functional right now.

### CODE REVIEW

**Comment by BPamukcuoglu** [comment]
It looks so nice, nice work, thanks for your effort, I did notice there is a bug with up vote/down vote functions but I assume that it's just a demo for now. The only thing, we may put the labels not under the title but on top of it. I believe that it will look a bit cooler and easy to distinguish. What you think about that ?

**Comment by araldortogul** [comment]
@BPamukcuoglu thank you for your review. Could you explain the bug with the upvote/downvote buttons? If there is something wrong I would like to fix it before merging.

For the labels, I think you are right. They would be better on top of the title. Could you check the labels again after I commit the new version?

**Comment by BPamukcuoglu** [comment]
My mistake it's actually a feature not a bug :) I don't know why but I expect to double clicking on up vote will increase count two times, however since every user have 1 vote, it should work like as it is. Sorry for the confusion

**Comment by BPamukcuoglu** [comment]
That looks nice thanks👍

**Review by BPamukcuoglu — APPROVED** [review]

**Pull request merged**
